### ISSUE TITLE
SAPUI5/OpenUI5 naming issue in README.md

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-language-assistant#145]
Dear colleagues,

can you please adopt the names of SAPUI5/OpenUI5 in the [README.md](https://github.com/SAP/ui5-language-assistant/blob/master/README.md):

> SAP UI5 >> SAPUI5 (written together, no whitespace!)

> SAP OpenUI5 >> OpenUI5 (without SAP in front!)

THX and BR,
Peter

**Comment by bd82** [comment]
@petermuessig is the README o.k now?

**Comment by petermuessig** [comment]
Looks great! BTW: same issue at ui5-typescript... 😉
