### ISSUE TITLE
Distinguish between SAPUI5 and OpenUI5 projects

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-language-assistant#239]
## Introduction

SAPUI5 and OpenUI5 have a different set of libraries available, but currently
the UI5 language server always creates the underlying data model using the SAPUI5 set of libraries.
This means that completions and validations are done against a possibly incorrect model, e.g:
- Suggestions offered from libraries that are not available.
- Not validation when using a Class tag that is not available in OpenUI5. 

## Open Questions 
- How does a UI5 project determine if its an OpenUI5 or SAPUI5 project?
- Is it perhaps a different question of the general set of "imported" libraries? rather then just two options (A vs B).

**Comment by rsletta** [comment]
The framework used for a UI5 project can be determined from the ["framework" configuration in UI5.yaml](https://sap.github.io/ui5-tooling/pages/Configuration/#framework-configuration).
![image](https://user-images.githubusercontent.com/12566124/113522489-15073800-95a1-11eb-967e-1ff243cec476.png)
![image](https://user-images.githubusercontent.com/12566124/113522493-1cc6dc80-95a1-11eb-8027-f406e9cdfb0f.png)

**Comment by bd82** [comment]
Thank you @rsletta that is good to know 👍

**Comment by piejanssens** [comment]
https://github.com/SAP/ui5-language-assistant/pull/469

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant with this change also the framework has been introduced in all relevant APIs. So, in theory it is possible to provide this metadata. With PR #469 the `ui5.yaml` has been read to identify the framework. But during discussions with different parties the better place to read the metadata from is the `manifest.json` but there we can only extract the `minUI5Version`. Will follow up to either add some metadata in the manifest.json or fallback to `ui5.yaml`.
