### ISSUE TITLE
Use technical user for npm uploads/github releases

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-language-assistant#244]

**Comment by mr25mr** [comment]
@bd82 this issue should be covered by github actions. We use manual triggering to upload to node.js and upload to github is done automatically when each PR is merged.

workflow file is located here https://github.com/SAP/ui5-language-assistant/actions/runs/6962317861/workflow

I close this issue, if you feel this is not covered, please reopen it. 
Thanks.
