### ISSUE TITLE
Support Multiple SAPUI5 versions

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-language-assistant#245]
## Downloading the UI5 metadata
- [ ] Dynamically obtain the set of libraries per version (see example [here](https://github.com/SAP/ui5-typescript/blob/master/test-packages/openui5-snapshot-test/lib/download-sdk.js))
   - Note that this metadata is only available since version 1.76.0
      - https://www.npmjs.com/package/@sapui5/distribution-metadata

## Configurability
- [ ] By default configure UI5 metadata version based on ui5.yaml.
- [ ] Optional override: Configure UI5 metadata version via a VSCode Settings.
- [ ] Fallback to some hard-coded recently released version.

## Test Flows
- [ ] Decide to set of versions to be tested.
   - List of maintained versions can be found in: [SAPUI5 Versions Maintenance Status](https://ui5.sap.com/versionoverview.html) 
- [ ] For a set of supported UI5 versions, transform the metadata to `UI5SemanticModel`.
- [ ] Run all `language-server` E2E tests using a set of supported versions.
       - Question: How to achieve high code reuse while also allowing different assertions (per version) for some test cases?
  
## Open Questions
- [ ] Are different `typeNameFixes` needed for different libraries or could a superset of all be used?
   - https://github.com/SAP/ui5-language-assistant/blob/366a950f2657685f023cee3e05646fb04c3a6af2/packages/language-server/src/ui5-model.ts#L139-L171
- [ ] Does the current implementation of the metadata caching in the language-server support versioning?

**Comment by bd82** [comment]
This is important not only from a product/feature perspective but also as the gap increases overtime.

**Comment by bd82** [comment]
I consider this also a kind of tech debt, as the usage of older and older hard-coded version
will potentially result in widening gap of what UI5 JSON SDK we can safely and successfully convert to a UI5 Semantic Model.

**Comment by piejanssens** [comment]
IMO this is really critical to support multiple UI5 version and determine it based on `minUI5Version` with a fallback to the official latest release (1.90).

**Comment by bd82** [comment]
> IMO this is really critical to support multiple UI5 version and determine it based on minUI5Version with a fallback to the official latest release (1.90).

Hello @piejanssens 

I completely agree.
Unfortunately there are no short term plans at this time to resolve this issue... 😢

**Comment by bd82** [comment]
Another URL to obtain version information of libraries:
- https://sapui5.hana.ondemand.com/resources/sap-ui-version.json

**Comment by piejanssens** [comment]
https://github.com/SAP/ui5-language-assistant/pull/469
