### ISSUE TITLE
Fragment inside aggregation "incorrectly" marked as error

### ISSUE THREAD

**Issue by qualiture** [SAP/ui5-language-assistant#274]
_Technically this is not a bug per se -- hence "incorrectly" in the title between quotes -- however the behavior described below does seem incorrect either way_

Version: 1.5.1

Imagine the following simplified XML page:

```xml
<Page>
    <content>
        <core:Fragment fragmentName="Fragment1" type="XML" />
        <core:Fragment fragmentName="Fragment2" type="XML" />
    </content>
</Page>
```

The ui5-language-assistant marks both fragment lines as:

> The class "Fragment" is under the aggregation "content" and must match the type "Control"

While this is technically correct, the Fragment "may contain" a valid control.

(Yes, it may also contain a potential invalid control, but I understand the difficulty of parsing the contents inside the `core:FragmentDefinition` tag of the fragment. However, I feel the chance of using an incorrect class inside the fragment is far lower than marking every `core:Fragment` class inside an aggregation as being incorrect)

**Comment by bd82** [comment]
Hello @qualiture 

Thanks for reporting this.

This VSCode extension is not aware of the contents of in-lined `Fragments` However I believe you are correct
and it would be better to simply ignore (whitelist) `Fragment` usages in this inspection.
The extension already implements certain heuristics and whitelists in other validation rules, so hopefully this would not be a large fix.

**Comment by bd82** [comment]
This is the relevant validation
- https://github.com/SAP/ui5-language-assistant/blob/master/packages/xml-views-validation/src/validators/elements/type-of-aggregation.ts#L16

And this is an example of a `whitelist` in **another** validation.
- https://github.com/SAP/ui5-language-assistant/blob/0692408f5b8a7ec9767097af9d885ce599c3a339/packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts#L85
- https://github.com/SAP/ui5-language-assistant/blob/0692408f5b8a7ec9767097af9d885ce599c3a339/packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts#L232-L241

**Comment by bd82** [comment]
Hello @qualiture. 

The fix should be released with the next version of the vscode extension.
I suspect the next version will be released late next week.

Cheers.

**Comment by qualiture** [comment]
@bd82, you're a star! Thanks for picking this up AND merging a fix so quickly!

Much appreciated!

**Comment by bd82** [comment]
Version 1.6.0 (with the fix) is now available on the VSCode marketplace.
- https://marketplace.visualstudio.com/items?itemName=SAPOSS.vscode-ui5-language-assistant
