### ISSUE TITLE
Evaluate using lerna "Fixed/Locked" mode.

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-language-assistant#287]
We are current using Lerna Independent mode.
- https://github.com/lerna/lerna#independent-mode

However this causes some issues:
- BREAKING CHANGES commits may touch multiple packages, resulting is less clear CHANGELOG.
- Managing multiple versions can be confusing, e.g < 1.0.0 versions behave differently on major bumps versus > 1.0.0 versions.
- All the packages here go into a single product (VSCode Ext), But with multiple changelogs its difficult to understand what actually changed in the VSCode Ext...

Perhaps we should use Fixed/Locked mode in lerna with a **single** centralized changelog for all packages?

**Comment by petermuessig** [comment]
Using fixed/locked mode already!
