### ISSUE TITLE
When will you update the UI5 version or make it configurable?

### ISSUE THREAD

**Issue by erlethor** [SAP/ui5-language-assistant#321]
Hi,

as UI5 is now on Version 1.82.2 I was wondering when you plan to push the version in the tools? 
And when do you plan to make it configurable?

Thanks,
Thorsten

**Comment by bd82** [comment]
Hello @erlethor 

I am afraid that In the short term there are no plans for updating the version or making the version configurable.

Cheers.
Shahar.

**Comment by bd82** [comment]
Closing this as the root issue is being tracked here:
- https://github.com/SAP/ui5-language-assistant/issues/245
