### ISSUE TITLE
Autocomplete in manifest.json files

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-language-assistant#326]
Hello,

Autocompletion in manifest.json is very useful, thank you for that!
However there are cases when the file has other name. In this case the file is not detected as being a manifest, so the feature doesn't work.
Take for example "myCardWithTranslations.json". I can rename it to "myCardWithTranslations.manifest.json", but it still won't be detected. It would be useful to check if the file name ends on manifest.json, so you can match all "*.manifest.json" files.

The best solution I see is to detect usage of the $schema keyword (https://json-schema.org/understanding-json-schema/reference/schema.html) and see if this piece of JSON is using the expected schema, but this would require also a change in the app descriptor.

Best regards,
Petar

**Comment by sapirpol** [comment]
Hi Petar,

Autocompletion in manifest.json files is not supported in design-time.
UI5 runtime fetches exact pattern for manifest.json and only files used in runtime get code assist.

Regards,
Sapir

**Comment by dimovpetar** [comment]
Hello @sapirpol 

I didn't mean for design-time, but normal JSON file editting.
Here is what I mean

- When my file is called manifest.json, I get suggestions as expected:
![image](https://user-images.githubusercontent.com/32839090/98646067-836e0400-233b-11eb-93dd-0f83577189c4.png)
- When my file is called myCard.json, I don't get suggestions:
![image](https://user-images.githubusercontent.com/32839090/98646190-b31d0c00-233b-11eb-840e-bb3b90e222ec.png)

manifests which describe cards (sap.card namespace) are often not called manifest.json

Best regards,
Petar

**Comment by bd82** [comment]
Hello @dimovpetar 

The file patterns for the manfiest json Schema (with provides the auto-complete support) are defined in the VSCode Ext sub-package:
- https://github.com/SAP/ui5-language-assistant/blob/master/packages/vscode-ui5-language-assistant/package.json#L23-L30

These **same** configuration is also part of the schema store catalog:
- https://github.com/SchemaStore/schemastore/blob/e23c66de0be49b744f8d9a7c35a900cdbd7e4216/src/api/json/catalog.json#L1966-L1974

So supporting `*.manifest.json` files patterns can be implemented by updating the VSCode Ext linked above.
Now the question remains: 
1. Is this a usable / common pattern to have files of "*.manifest.json" pattern in UI5 applications?
    - @codeworrior @petermuessig **WDYT**?

**Comment by codeworrior** [comment]
No, for UI5 applications this is neither usable nor common. The name manifest.json is mandatory.

But what @dimovpetar aims at, is a different scenario. **Cards** are not applications, they have a manifest type of their own (`"sap.app"/"type":"card"`) . I'm not familiar with naming conventions for them. I would suggest to contact @maddel to discuss this.

As far as I known, schema store as well as tools relying on it only take file names into account, not file content. Therefore, the (theoretically perfect) idea of checking $schema is not of any use in existing tools. Whether SAP's own code could do this and check the content, you know better than me, I guess.

**Comment by bd82** [comment]
The `$schema` property is a feature of the JSON validation in vscode.
- https://code.visualstudio.com/Docs/languages/json#_mapping-in-the-json

There are other ways to configure Schema mappings in VSCode, e.g:
- https://code.visualstudio.com/Docs/languages/json#_json-schemas-and-settings

So I would expect this to **already work**.

@dimovpetar could you try these custom mapping options and see if they work for your use case?

**Comment by dimovpetar** [comment]
Hello @bd82 ,

Yes, the `$schema` property already works in VS Code, but it makes the JSON valid invalid, because it is not allowed https://raw.githubusercontent.com/SAP/ui5-manifest/master/schema.json . My opinion is that this is the best solution, which would work in all cases, and also `recommended that all JSON Schemas have a $schema entry, which must be at the root`  (from the official json-schema documentation). But this is out of scope of this project. 
I was not aware of the other mapping options, so I consider this as resolved.

Best regards,
Petar
