### ISSUE TITLE
Add support for autopopinmode / importance tags for responsive table

### ISSUE THREAD

**Issue by my0name** [SAP/ui5-language-assistant#334]
Hi,
I've encountered a problem in VSCode (latest) and the UI5 Language Assistant 1.6.0.
If I'm using the autoPopinMode property of the table or the importance property in the columns, I'm getting told, that they're not supported (see screenshot)

![column](https://user-images.githubusercontent.com/32565399/101618542-70ba1e00-3a12-11eb-80ba-3bf78b52c45a.png)

**Comment by bd82** [comment]
The `importance` property was added in UI5 1.76
 
![image](https://user-images.githubusercontent.com/4233843/101774446-ca941400-3af6-11eb-9c75-e3783b5929f5.png)

However this VSCode extension is hard-coded to use version 1.71.14. Which is why you see an error.

Resolving this depends on #245

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469
