### ISSUE TITLE
UI5 Artefact sap.ui.core.ExtensionPoint is not found

### ISSUE THREAD

**Issue by flovogt** [SAP/ui5-language-assistant#387]
Hi team,
I've created a simple XMLView and used the `sap.ui.core.ExtensionPoint` artefact.
Unfortunately, the ui5 language assistant tell me that the ExtensionPoint is not included in the `sap.ui.core` namespace, but it is.
![image](https://user-images.githubusercontent.com/34711402/114016567-43b83380-986b-11eb-903e-d4a5435293e2.png)

See https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/core/ExtensionPoint.js

**Comment by codeworrior** [comment]
`ExtensionPoint` is not a control/element and therefore the `ui5-language-assistant`'s standard mechanisms for controls don't apply to it. I guess it has to be handled as a special case, similar to the `FragmentDefinition`.

**Comment by bd82** [comment]
For reference here is the handling for `FragmentDefinition`.
- https://github.com/SAP/ui5-language-assistant/blob/b583299d11cf78c9c669a02c00714288b4aada99/packages/xml-views-validation/src/validators/elements/unknown-tag-name.ts#L236-L245

Note that expending this will only disable the errors, not provide full XML editor support for `ExtensionPoint`

**Comment by bd82** [comment]
Thanks @flovogt for the PR fixing this 👍

**Comment by bd82** [comment]
keeping open until a new version is released

**Comment by flovogt** [comment]
> Thanks @flovogt for the PR fixing this 👍

Thanks @bd82 for your support. Happy to help 🎉

**Comment by bd82** [comment]
1.7.2 is finally on the marketplace.
- https://marketplace.visualstudio.com/items?itemName=SAPOSS.vscode-ui5-language-assistant
