### ISSUE TITLE
manifest.json cannot be analyzed in TypeScript projects

### ISSUE THREAD

**Issue by mschleeweiss** [SAP/ui5-language-assistant#424]
I was playing around with the new Typescript environment:

https://github.com/SAP-samples/ui5-typescript-helloworld

I noticed that the manifest wasn't analyzed by the language assistant. No auto complete, no warnings/errors.

I guess this is because in Typescript the source code will be placed in `/src` and not `/webapp` (`/webapp` is where the transpiled JavaScript is put when the npm task `watch:ts`).

I would love to use the language assistant in Typescript projects as well, please consider implementing this.

**Comment by bd82** [comment]
Hello @mschleeweiss.

 sorry for the late response.
I will have to check with some collegues how "final" the location of the manifest.json is 
and if this should be supported.
 
In the meanwhile you can define custom schemas in VSCode via
- https://code.visualstudio.com/docs/languages/json#_mapping-in-the-user-settings

**Comment by bd82** [comment]
Hello again @mschleeweiss 

I released a new version to github releases.
- https://github.com/SAP/ui5-language-assistant/releases/download/v3.1.0/vscode-ui5-language-assistant-3.1.0.vsix

It would take some time for a new release to VSCode marketplace (processes...)
But you can download and tryout the new version directly from the GH releases link above in the meanwhile...
