### ISSUE TITLE
Hard-Coded UI5 Version (known limitation)

### ISSUE THREAD

**Issue by the-docta** [SAP/ui5-language-assistant#428]
the hard-coded UI5 Version (listed in known limitations of the VSCode Extension) 

could we have a preference setting, where we could set the version that is to be used?

something like 

```
UI5LanguageAssistant.codeAssist.ui5version = "1.84.4"
```
maybe along with "sapui5/openui5" switch

**Comment by GuillaumedesPommareSAP** [comment]
> The #413 is just an early WIP for this topic, one which I unfourntaly did not have time to complete...

Would it be possible to at least upgrade hard-coded version to latest LTS (1.84)? To have something up-to-date, not close to cloud versions, but stable enough ?

**Comment by nxthor** [comment]
Hi!
What about the ui5.yaml file for the used version? I guess every project would have to define the targeted version there anyway, or do I miss cases?

**Comment by GuillaumedesPommareSAP** [comment]
> Hi! What about the ui5.yaml file for the used version? I guess every project would have to define the targeted version there anyway, or do I miss cases?

A configuration option would be great. How it is done is another story, not everyone is using ui5-cli so not every project defines a ui5.yaml file. Here the main issue is that this extension hardcodes one version of UI5 and has no been updated for a while, so you get error on valid XML files, that is not very useful.

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469
