### ISSUE TITLE
TS Compilation issues

### ISSUE THREAD

**Issue by uxkjaer** [SAP/ui5-language-assistant#433]
Hello, 
I'm trying to help a bit with the proxy issues. However I get a fair few typescript compilation errors  on the text edit range. 
packages/language-server/test/completion-items-utils.ts:120:45 - error TS2339: Property 'range' does not exist on type 'TextEdit | InsertReplaceEdit'.
  Property 'range' does not exist on type 'InsertReplaceEdit'.

**Comment by bd82** [comment]
Hello @uxkjaer 

How are you compling the project?

I've done fetched/rebased on master and did not encounter any issues either while running the whole CI process `yarn run ci`
or when running the compiler in watch mode `yarn run compile:watch`

**Comment by bd82** [comment]
Maybe the contribution guide could be of assistance?
- https://github.com/SAP/ui5-language-assistant/blob/master/CONTRIBUTING.md

**Comment by uxkjaer** [comment]
I've followed the guide. When I run yarn compile I get the Ts errors

**Comment by uxkjaer** [comment]
Hmmm deleted and started again and it works now. Must have done some installs with npm instead of yarn.
