### ISSUE TITLE
Button type "Success" not known

### ISSUE THREAD

**Issue by AlexanderK22** [SAP/ui5-language-assistant#435]
The button type "Success" is not known to the language assistant and therefore marks the type as an error. The type needs to be added.

![image](https://user-images.githubusercontent.com/60352903/144590563-56f40580-7af7-4696-8a19-b5832e9b5bd9.png)

**Comment by OTTOxMarc** [comment]
https://sapui5.hana.ondemand.com/1.71.14/#/api/sap.m.ButtonType

In the given UI5 version (1.71) the button type `Success` is not available. This new type was added in 1.73

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469
