### ISSUE TITLE
Update Hard-Coded UI5 version

### ISSUE THREAD

**Issue by bd82** [SAP/ui5-language-assistant#436]
- [ ] Pick `version`
- [ ] Update JSON Schema to `version`
  - https://github.com/SAP/ui5-language-assistant/blob/master/packages/semantic-model/resources/sap-ui-library-api.json
- [ ] generate`.d.ts` for the JSON schema
      - https://github.com/SAP/ui5-language-assistant/blob/master/packages/semantic-model/package.json#L38
- [ ] update the `version` the language server is using
      - https://github.com/SAP/ui5-language-assistant/blob/master/packages/language-server/src/ui5-model.ts#L15
- [ ] update the `version` used in tests and fix assertions
- [ ] manual regression tests for productive flows.

**Comment by richard-bruenning** [comment]
Is there Any News on this? I would like to use a higher version.

**Comment by bd82** [comment]
I am afraid not, there was some attempt to assign some capacity towards this topic,
but it was stopped midway due to time overrun and lack of capacity.

The team that is responsible for this repo, (imho) unfortunately lacks the capacity to
promote this issue... 😢

**Comment by piejanssens** [comment]
https://github.com/SAP/ui5-language-assistant/pull/469

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469

**Comment by GuillaumedesPommareSAP** [comment]
> The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.
> 
> Fixed with PR #472 #469

Hello @petermuessig ,
I can see the release on this project but nothing on the one published on vscode marketplace. Is it planned to get it also updated or is there any alternative to install it ?

**Comment by piejanssens** [comment]
@GuillaumedesPommareSAP https://github.com/SAP/ui5-language-assistant/issues/476

**Comment by petermuessig** [comment]
HI @GuillaumedesPommareSAP ,

as of today, the shipment to VSCode marketplace needs to be coordinated with respect to the delivery channels. I expect the availability in mid of September. Until then, you can pick the VSIX from here and install it manually. I'll check whether we can change that in future.

Best, Peter

**Comment by GuillaumedesPommareSAP** [comment]
> HI @GuillaumedesPommareSAP ,
> 
> as of today, the shipment to VSCode marketplace needs to be coordinated with respect to the delivery channels. I expect the availability in mid of September. Until then, you can pick the VSIX from here and install it manually. I'll check whether we can change that in future.
> 
> Best, Peter

Sure, this is my fallback option. Thanks !
Guillaume
