### ISSUE TITLE
Topic Links in api.json are not correctly translated into valid URLs

### ISSUE THREAD

**Issue by ehwg** [SAP/ui5-language-assistant#444]
When getting information on the table tag in a view xml the mentioned link

https://sapui5.hana.ondemand.com/1.71.14/#/api/topic:5eb6f63e0cc547d0bdc934d3652fdc9b[](https://github.wdf.sap.corp/storage/user/15976/files/1d275680-8f6c-11ec-9fea-e8f59b02e738)

does not exist.

![image](https://user-images.githubusercontent.com/7009080/154635060-6a6ec1e2-d660-47d8-9d66-d000cdd3022a.png)

Steps to Reproduce

Go to view.xml file
show context information for table
Click on 'hyperlink'
See error 'The requested resource was not found'
Screenshots
image

Version/Components/Environment
Fiori tools Version of extensions in this release: 1.4.7

best regards 
Eckard.

**Comment by bd82** [comment]
Thank you for reporting this @ehwg 

I've done a quick triage and it seems that all of these "topic links" are not correctly translated.
For example: `sap.m.Text` has the following description in the api.json
```
      "description": "The <code>Text</code> control can be used for embedding longer text paragraphs, that need text wrapping, into your app. If the configured text value contains HTML code or script tags, those will be escaped.\n\nAs of version 1.60, you can hyphenate the text with the use of the <code>wrappingType</code> property. For more information, see {@link topic:6322164936f047de941ec522b95d7b70 Text Controls Hyphenation}.\n\n<b>Note:</b> Line breaks will always be visualized except when the <code>wrapping</code> property is set to <code>false</code>. In addition, tabs and whitespace can be preserved by setting the <code>renderWhitespace</code> property to <code>true</code>.",

``` 

which includes `{@link topic:6322164936f047de941ec522b95d7b70 Text Controls Hyphenation}` which is then transformed to `https://sapui5.hana.ondemand.com/1.71.14/#/api/topic:6322164936f047de941ec522b95d7b70` url which is invalid.

**Comment by bd82** [comment]
@matz3 @codeworrior @petermuessig @RandomByte do you know how we should transform such topic links?

**Comment by bd82** [comment]
So after looking at the UI5 SDK m.Text page I now understand how it should be done.

`{@link topic:6322164936f047de941ec522b95d7b70...` should become
`https://sapui5.hana.ondemand.com/1.71.14/#/topic/6322164936f047de941ec522b95d7b70 instead of
`https://sapui5.hana.ondemand.com/1.71.14/#/api/topic:6322164936f047de941ec522b95d7b70`

- remove `/api/` part
- `topic:` becomes `topic/
