### ISSUE TITLE
sap.m.ExpandableText is not recognized

### ISSUE THREAD

**Issue by yoppieariesthio** [SAP/ui5-language-assistant#464]
It gives warning message when you use sap.m.ExpandableText element.

I code at SAP BAS and using sapui5 version 1.96.6

![image](https://user-images.githubusercontent.com/102799135/181729668-7fba3150-58d7-434a-b07b-9c1eb5c3c8f1.png)

**Comment by petermuessig** [comment]
The latest version `3.2.1` brings multi-version support for the UI5 Language Assistant. The version is derived from the `minUI5Version` of the closest `manifest.json` and resolved against the latest available and supported versions from UI5.

Fixed with PR #472 #469
