### ISSUE TITLE
Outdatet SAP UI5 Version 1.71.14 in @ui5-language-assistant/language-server Error

### ISSUE THREAD

**Issue by JoernSP** [SAP/ui5-language-assistant#468]
Hello,
after adding a new ..view.xml file the Code Completion for the xml assistant throws following errors.

The 1.71.14 is not longer supported by SAP.

![image](https://user-images.githubusercontent.com/110963953/183829353-f259d034-e557-414d-b79f-7c1ad109749b.png)

Can i manually change the used ui5 version or  must it be fixed by SAP?

Thanks

Best regards
Jörn

**Comment by JoernSP** [comment]
I use **VS Code** for developing.

**Comment by hannemac** [comment]
Same here:
![image](https://user-images.githubusercontent.com/6243420/183836069-d24aee7a-1e98-4c1a-bc3b-ef37300b1ca9.png)

Versions:
![image](https://user-images.githubusercontent.com/6243420/183836258-acb92703-9a06-4928-80e3-cfd4bdd6be14.png)

**Comment by NAVI-91** [comment]
same here...

![image](https://user-images.githubusercontent.com/17800881/184464243-8e1a2e7a-195b-4fac-9a5c-2e1871a2886d.png)

**Comment by JoernSP** [comment]
@petermuessig : Thanks for the fixes,  is it already in the UI5 Extension as a new  version?  Or do i have to wait a little while?

Thanks.
