### ISSUE TITLE
Updating the min version or the ui5.yaml framework doesn't update the version in the language assistant

### ISSUE THREAD

**Issue by uxkjaer** [SAP/ui5-language-assistant#482]
Steps to reproduce:
1. Install a project using easy-ui5
2. Open VS code and check the version in the view (1.71.49)
3. Move the webapp and ui5.yaml file from uimodule to root
4. Open vscode and check version (1.71.49)
5. Update the min version to 1.102.2
6. Open vscode and check version (1.71.49)

**Comment by petermuessig** [comment]
This is the latest package with deriving the framework from the `ui5.yaml` and proxy support - the version is derived from the `manifest.json`:

[vscode-ui5-language-assistant-3.2.1.vsix.zip](https://github.com/SAP/ui5-language-assistant/files/9412800/vscode-ui5-language-assistant-3.2.1.vsix.zip)

**Comment by petermuessig** [comment]
[vscode-ui5-language-assistant-3.2.1-proxy.vsix.zip](https://github.com/SAP/ui5-language-assistant/files/9412880/vscode-ui5-language-assistant-3.2.1-proxy.vsix.zip)

**Comment by petermuessig** [comment]
This is a false positive - fixed and confirmed by @uxkjaer
