### ISSUE TITLE
UI5 version is outdated

### ISSUE THREAD

**Issue by Nico31300** [SAP/ui5-language-assistant#487]
Hello,

UI5 Language assistant use an hardcoded UI5 library 1.71.14 and this version is outdated and removed from SAP CDN

example: https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/chart/designtime/api.json
<img width="408" alt="2022-08-31_15-21-57" src="https://user-images.githubusercontent.com/16101587/187688498-bb32ed86-62d2-4ba1-9ca9-868e869cdea4.png">

I work with Business Application Studio, so files are cache in  this repo /home/user/.theia/globalStorage/saposs.vscode-ui5-language-assistant. But for new library I have the message:
`Unknown namespace: "sap.ui.core.mvc"UI5 Language Assistant`

Cause from output console with trace activated:
```
{
  "label": "@ui5-language-assistant/language-server",
  "level": "error",
  "message": "Could not read UI5 resources from",
  "time": "2022-08-31T12:59:20.642Z",
  "url": "https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ui/fl/designtime/api.json"
}
```

Could you please change the UI5 version to a non outdated one ?

Thank you,

Nicolas Couret

**Comment by OTTOxMarc** [comment]
How where you able to install the add on in BAS in the first place? I can't find it there in the registry. I manually uploaded the VSIX to BAS, installed it and it says "Installation complete" but I still don't see it :(

**Comment by Nico31300** [comment]
> How where you able to install the add on in BAS in the first place? I can't find it there in the registry. I manually uploaded the VSIX to BAS, installed it and it says "Installation complete" but I still don't see it :(

When you create a SAP Fiori Workspace on Business Application Studio, UI5 Language Assistant is bundled in the workspace. 

You can see it in Built-In section
![image](https://user-images.githubusercontent.com/16101587/187758442-f6a43295-1a9b-4fe8-b354-8d64cbcc95c9.jpeg)

**Comment by OTTOxMarc** [comment]
Got it. Still weird that one can't install the VSIX, would solve this problem without any effort on SAP's side.

**Comment by alpyesilgul** [comment]
I have the same issue. Is there any solution?

**Comment by sydrack033** [comment]
I have the same issue. Is there any solution?

**Comment by petermuessig** [comment]
Hi all,

right now, you need to manually install the VSIX from the 3.3.1 release:
https://github.com/SAP/ui5-language-assistant/releases/tag/v3.3.1

Download the VSIX and use the option "Install from VSIX..." in the extensions "..." menu.

We are working on making the 3.3.1 release available in the VSCode market place. Due to delivery processes this takes a bit of time. 

Cheers,
Peter

Related issues: 
* #468
* #436 
* #476

**Comment by Nico31300** [comment]
Ok thank you for the information. We will wait the ne version availability on BAS then. 

If we can have a date it could be great if it could speed up the process i can open an incident.

**Comment by boghyon** [comment]
> Unknown namespace: "sap.ui.core.mvc"

@Nico31300 Could you confirm that the issue is also fixed by now in SAP Business Application Studio?

**Comment by Nico31300** [comment]
Hello,
I confirm that issue us fixed in BAS.
