### ISSUE TITLE
XML code completion does not work

### ISSUE THREAD

**Issue by dflasch** [SAP/ui5-language-assistant#493]
Hello, 

when I try to execute code completion on a xml-view in my ui5 project, the code completion does not work as expected. 
I can see suggestions for tags and properties that I have already used in my view, but no other suggestions. 

In my terminal I can find an error, when the language assistant tries to fetch data from https://sapui5.hana.ondemand.com/1.71.14/test-resources/sap/ui/core/designtime/api.json". 

![image](https://user-images.githubusercontent.com/16955360/188657144-0c620695-dc57-483f-99a4-6c9706b6c815.png)

If I try to access the url in my browser, the page says the version was remove because it's deprecated.

**Comment by dflasch** [comment]
In the meantime I have built the newest version from this github repo, that should fix the issue. Unfortunately the newest version doesn't work for me aswell. The plugin never gets activated and so the code completion does not work.

**Comment by alpyesilgul** [comment]
I have the same issue, is there any solution? There is the same problem in Business Application Studio and they presented a [solution](https://github.com/SAP/ui5-language-assistant/issues/487). But for the VSCode extension, I think there must be updated.

**Comment by petermuessig** [comment]
Hi, the extension will be updated soon in BAS and the VSCode marketplace with the next BAS release end of September. The release process is coupled to internal processes so far and therefore we can't speed this up for the moment. What you can do is to try the [VSIX for 3.3.1](https://github.com/SAP/ui5-language-assistant/releases/download/v3.3.1/vscode-ui5-language-assistant-3.3.1.vsix) - this should by default select the latest available 1.71 version and in case of maintaining a minUI5Version in the sap.ui5 dependencies section in the `manifest.json` select the closest available possible version. It also is able to distinguish between OpenUI5 and SAPUI5 by maintaining the framework name in the `ui5.yaml` but by default uses SAPUI5.

**Comment by petermuessig** [comment]
What I noticed, you can even install it in BAS. Upload the VSIX to the local workspace, install VSIX in the extensions tab from local workspace and the restart the workspace (stop and start it again). It works for me - I can use the 3.3.1 version in my workspace now.

**Comment by dflasch** [comment]
Thanks @petermuessig for your answer. Unfortunately installing version 3.3.1 in vscode does not solve the issue for me. I still don't have any code completion suggestion in my XML-Views. I have defined a minversion in my manifest.json and set sapui5 in my ui5.yaml file. Are there any other prerequisites for the code completion?

**Comment by petermuessig** [comment]
@dflasch , can you share your project somehow with me? Is this possible?

**Comment by petermuessig** [comment]
BTW: tomorrow, September 28th, the version 3.3.0 (which is the same like 3.3.1 - as this was a release test) will be available in BAS and the VSCode marketplace.

**Comment by dflasch** [comment]
@petermuessig ok, thanks for the update. I have generated a demo application in my public repo: [ui5-test-vscode-code-completion](https://github.com/dflasch/ui5-test-vscode-code-completion). I have the same issue there. I have set the min-Verison in the manifest.json an chose the sapui5 framework in ui5.yaml.

**Comment by bd82** [comment]
3.3.0 is out of the VSCode marketplace.

**Comment by dflasch** [comment]
I've installed 3.3.0 from the marketplace. Solved the issue for me, code completion works like a charm! Thanks :)
