### ISSUE TITLE
Feature Request: Set/Change the sapui5.com URL

### ISSUE THREAD

**Issue by hauntedhill** [SAP/ui5-language-assistant#520]
Hello,

i am working in an environment without connection to the internet. I would like to use the plugin but for that i need a setting for the URL and reject unauthorized HTTPS.

The reason is that we download our SAPUI5 version from https://tools.hana.ondemand.com/#sapui5 and provide this over an https server localy.

Is this possible?

Thanks and Regards

Christian

**Comment by petermuessig** [comment]
Hi @hauntedhill,

no, unfortunately. Right now the URLs to the CDN are hard-coded in the plugin as we so far always assume that you are connected to the Internet either directly or via proxy. Would you expect to load the `api.json` in your case from a internally hosted SAPUI5 version on a web server or maybe from the local file system? The only thing which is a bit tricky then is that there is no real multi-version support anymore. The plugin can then only provide the code completion for the downloaded version. So maybe an option would be to provide an option to configure a local version. What would you prefer? An internal server or a local folder? 

Best regards,
Peter

**Comment by hauntedhill** [comment]
Hi,

we setup an internal https-web-server with the same structur as https://sapui5.hana.ondemand.com/.

For example:

https://sapui5.mycompany.lan:8080   <= Default (or latest sapui5-version for my company)
https://sapui5.mycompany.lan:8080/1.71/  <= Other version

But at the end it would be perfect for me to configure an internal https-web-server url. In my case no multi-version support is needed.

Thanks and Regards,
Christian

**Comment by kirkpabk** [comment]
Our organization also has concerns with external "active" connectivity.  Do you have documented specifications for the SAP VS Code Extensions for all of the end-points and content types from which to define proxy parameters?

**Comment by hitesh-parmar** [comment]
> Hi,
> 
> we setup an internal https-web-server with the same structur as https://sapui5.hana.ondemand.com/.
> 
> For example:
> 
> https://sapui5.mycompany.lan:8080 <= Default (or latest sapui5-version for my company) https://sapui5.mycompany.lan:8080/1.71/ <= Other version
> 
> But at the end it would be perfect for me to configure an internal https-web-server url. In my case no multi-version support is needed.
> 
> Thanks and Regards, Christian

Hello @hauntedhill If I understand correctly, you are able to use UI5 language assistant in offline mode, right?

**Comment by hauntedhill** [comment]
@hitesh-parmar with the version from nevember no. Actually i didnt try any newer versions.

**Comment by MN-public** [comment]
@hauntedhill @hitesh-parmar 
Working offline is not yet possible but we are looking into it. We will inform you once it is provided with some info on how to configure it

**Comment by MN-public** [comment]
Offline support enabled with the latest version, closing this enhancement request.
