### ISSUE TITLE
Visual Studio Code UI5 Language Assistant crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by Denis-bdk** [SAP/ui5-language-assistant#524]
The UI5 Language Assistant is crashing and restarting several times, until an error message "The UI5 Language Assistant server crashed 5 times in the last 3 minutes. The server will not be restarted." shows up.

[Output Log.txt](https://github.com/SAP/ui5-language-assistant/files/10091128/Output.Log.txt)
<img width="338" alt="Fehlermeldung" src="https://user-images.githubusercontent.com/118740289/203960860-739653ac-95fe-45dd-b0fd-19a4ce0e8490.png">

**Comment by petermuessig** [comment]
@Denis-bdk are you behind a proxy? The language assistant tries to open the following URL: [https://ui5.sap.com/1.71.49/resources/sap-ui-version.json](https://ui5.sap.com/1.71.49/resources/sap-ui-version.json) but it doesn't seem to be available?

**Comment by Denis-bdk** [comment]
@petermuessig yes, it is behind a proxy.

**Comment by petermuessig** [comment]
The proxy configuration can be set via env variables as the fetch call is using the `proxy-from-env` module to apply the proxy configuration: https://github.com/SAP/ui5-language-assistant/blob/master/packages/language-server/src/fetch.ts#L10

Setting the proxy like described here as env variables should fix it:
https://www.npmjs.com/package/proxy-from-env

```
HTTPS_PROXY=https://proxy:8443
```

**Comment by mr25mr** [comment]
@Denis-bdk can you please check if this PR https://github.com/SAP/ui5-language-assistant/pull/525 solves your issue?

**Comment by Denis-bdk** [comment]
@petermuessig Thanks for your help! I have set the proxy configuration via env variables. The Extension does not crash several times anymore instead there is a new error:

{
  "label": "@ui5-language-assistant/language-server",
  "level": "error",
  "message": "Could not read version information",
  "time": "2022-12-01T12:20:00.792Z",
  "url": "https://ui5.sap.com/1.71.49/resources/sap-ui-version.json"
}

**Comment by Denis-bdk** [comment]
@petermuessig No problem, yes sometimes the proxy needs an authentication. I can also open the URL in my browser.

**Comment by petermuessig** [comment]
Have you tried to set the env variable with user and password? 

`http_proxy=http://user:password@proxyIP:proxyPort/`

**Comment by Denis-bdk** [comment]
@petermuessig Yes I have tried now, and it finally works. Thank you very much!
I would also like to suggest the feature to configure the proxy settings in VS Code. For example in the UI5 Language Assistant Extension Settings.

**Comment by Nioniotte** [comment]
Hi, 

I have the same issue. I tried with and without proxy env variable or with and without proxy and user+password. The error are always :   errno: 'SELF_SIGNED_CERT_IN_CHAIN',

It is behind a proxy (DIRECT).

**Comment by Naxos84** [comment]
I have the same issue but with a different error detail.

I'm using version 4.0.3 (2023-01-30)

The message I get is:

> TypeError: Cannot read properties of undefined (reading 'dataSource')
>     at getMainService (c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110741:140)

So I checked the code of the extension and that boils down to:

(Notice I added the `console.log`'s on purpose.)
```js
/**
 * Get main service defined in manifest under `sap.ui5->models`
 * @param manifest manifest of an app
 */
function getMainService(manifest) {
	console.log({manifest});
    var _a, _b, _c, _d;
    const model = (_b = (_a = manifest["sap.ovp"]) === null || _a === void 0 ? void 0 : _a.globalFilterModel) !== null && _b !== void 0 ? _b : "";
	console.log({model});
    return (_d = (_c = manifest["sap.ui5"]) === null || _c === void 0 ? void 0 : _c.models) === null || _d === void 0 ? void 0 : _d[model].dataSource;
}
```

The resulting log is the following

```
{
  manifest: {
    _version: '1.12.0',
    'sap.app': {
      id: 'com.th.examples.ui5.ui5examples',
      type: 'application',
      i18n: 'i18n/i18n.properties',
      title: '{{appTitle}}',
      description: '{{appDescription}}',
      applicationVersion: [Object]
    },
    'sap.ui': { technology: 'UI5', icons: {}, deviceTypes: [Object] },
    'sap.ui5': {
      rootView: [Object],
      dependencies: [Object],
      handleValidation: true,
      contentDensities: [Object],
      models: [Object],
      routing: [Object]
    }
  }
}
{ model: '' }
c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110741
    return (_d = (_c = manifest["sap.ui5"]) === null || _c === void 0 ? void 0 : _c.models) === null || _d === void 0 ? void 0 : _d[model].dataSource;
                                                                                                                                           ^

TypeError: Cannot read properties of undefined (reading 'dataSource')
    at getMainService (c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110741:140)
    at extractManifestDetails (c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110802:35)
    at Object.getManifestDetails (c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110836:12)
    at async Object.getContext (c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:110228:29)
    at async c:\Users\matkolley\.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:127469:25
[Error - 11:29:42 AM] The UI5 Language Assistant server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

I know that I don't have a model with the name "".

What could cause that issue?
Do you need more information?
