### ISSUE TITLE
Hard-coded (1.71.x) version if VSCode Workspace has multiple Projects

### ISSUE THREAD

**Issue by juergenbosch** [SAP/ui5-language-assistant#537]
My VSCode Workspace has multiple projects. If i open any xml file always Version 1.71.x is used for the language assistant. 
<img width="1626" alt="vscode-langassi" src="https://user-images.githubusercontent.com/77337792/207636185-cce47840-4600-4cd8-9fcd-3cd513ff778d.png">

In all projects i have defined for each manifest.json as "minUI5Version": "1.108.0".
<img width="375" alt="vscode-manifest" src="https://user-images.githubusercontent.com/77337792/207636305-803a95cb-f1e2-4606-8cf2-0b8981e3df77.png">

If i open only one project in VSCode the language assistance use the defined Version in the manifest.json.
How is it possible to has this also in my multi project Workspace?

**Comment by MN-public** [comment]
Hello, could you please check it with the latest version 4.0.3? There should be a fix for workspaces with multiple projects

**Comment by Idefix2412** [comment]
Now it works.
Thanks
