### ISSUE TITLE
Language server crashes when ui5.yaml contains multiple documents

### ISSUE THREAD

**Issue by vonBrax** [SAP/ui5-language-assistant#555]
The language server crashes if you current project ui5.yaml contains more than one document (ie, separated with "---")

The error message is:

YAMLError: Error parsing YAML document
Source contains multiple documents; please use YAML.parseAllDocuments()
    at new YamlDocument (.vscode\extensions\saposs.vscode-ui5-language-assistant-4.0.3\node_modules\@ui5-language-assistant\language-server\dist\server.js:7101:19)

The "cross-project reversed stack-trace" is more or less:

at onCompletion: https://github.com/SAP/ui5-language-assistant/blob/82961132b90ac3decd7cb83c11f3c853899cd723/packages/language-server/src/server.ts#L125

at getContext: https://github.com/SAP/ui5-language-assistant/blob/6b35d43e91753eef6bcd215d894ce69472b77863/packages/context/src/api.ts#L46

at getCustomViewId: https://github.com/SAP/ui5-language-assistant/blob/ce59328b229cd55a2b2e606afd50785feffab5a5/packages/context/src/manifest.ts#L216

at findAppRoot: https://github.com/SAP/ui5-language-assistant/blob/ce59328b229cd55a2b2e606afd50785feffab5a5/packages/context/src/utils/project.ts#L100

at getAppRootFromWebappPath: https://github.com/SAP/open-ux-tools/blob/11c8f5dca173b5409b2f6969ba78da65dfcd625a/packages/project-access/src/project/search.ts#L123

at getWebappPath: https://github.com/SAP/open-ux-tools/blob/11c8f5dca173b5409b2f6969ba78da65dfcd625a/packages/project-access/src/project/ui5-config.ts#L17

at UI5Config.newInstance: https://github.com/SAP/open-ux-tools/blob/11c8f5dca173b5409b2f6969ba78da65dfcd625a/packages/ui5-config/src/ui5config.ts#L39

at YamlDocument.newInstance: https://github.com/SAP/open-ux-tools/blob/11c8f5dca173b5409b2f6969ba78da65dfcd625a/packages/yaml/src/yaml-document.ts#L31

at YamlDocument.constructor: https://github.com/SAP/open-ux-tools/blob/11c8f5dca173b5409b2f6969ba78da65dfcd625a/packages/yaml/src/yaml-document.ts#L41

As the error message suggests, the issue can be fixed by using YAML.parseAllDocuments() instead of YAML.parseDocument() (tested locally and it seems to work).

I know the offending line of code is on another SAP repository, but I thought it would make more sense to open this issue here.

env:
@ui5-language-assistant/language-server: 4.0.3
node: 19.4.0
npm: 9.3.1
OS: Windows 10

**Comment by Klaus-Keller** [comment]
Hi @vonBrax, 

Thanks for the thorough error analysis, that helps to provide a timely fix for the issue. As the root cause is in module `@sap-ux/yaml`, I've created ticket https://github.com/SAP/open-ux-tools/issues/892.

**Comment by tobiasqueck** [comment]
Dear @SAP/ui5-language-assistant-members please consume the latest version of the `@sap-ux/yaml` module. A fix (https://github.com/SAP/open-ux-tools/pull/906) for this error has been merged.

**Comment by MN-public** [comment]
@vonBrax This is now fixed in the master version of UI5 Language Assistant. If you like, you can build a .vsix installer from the updated sources or wait until a new version is officially released to VSC marketplace next week.

Once you check it, it would be great to hear from you whether it foxes your issue.

**Comment by vonBrax** [comment]
I've just tested in version 4.0.5 and the bug seems to be fixed, so I'm closing this issue.

Thank you for looking into it and for the amazing work!
