### ISSUE TITLE
footer aggregation in sap.m.Dialog reported as error

### ISSUE THREAD

**Issue by wurst0815** [SAP/ui5-language-assistant#565]
When using a sap.m.Dialog in a fragment and trying to use footer aggregation, I get an error.
![image](https://user-images.githubusercontent.com/13557494/220291255-815d0a0e-272e-46c3-b8d5-84fcb1eff4e9.png)

But according to the API Reference, this is not true
![image](https://user-images.githubusercontent.com/13557494/220291449-c12d57f2-39a2-4d4c-aec7-1ceec4a20c71.png)

**Comment by voicis** [comment]
Hi,

It seems that `footer` aggregation was recently added in UI5 version `1.110`. UI5 language assistant looks in the `manifest.json` for the value of `minUI5Version` and preforms the checks based on the version specified there. You can see what version is used by the UI5 language assistant for a particular file in the status bar like this:
![image](https://user-images.githubusercontent.com/6721493/220327679-2ff419db-1466-40d8-b692-43b9c3b00a79.png)

Please check what UI5 version is specified in your `manifest.json` file and if the aggregation is available for that particular version. If its not available in that version and you want to use this feature, then you should update `minUI5Version` to a version where it is available.

**Comment by wurst0815** [comment]
Hi,
that was the trick, thank you.
