### ISSUE TITLE
Feature Request: Formatting capabilities in UI5 Language Assistant extension for XML Files

### ISSUE THREAD

**Issue by sammok83** [SAP/ui5-language-assistant#569]
Hi,

As per this thread I've started:
[SAP Fiori Tools XML Annotation Server XML Formatting](https://answers.sap.com/questions/13832471/sap-fiori-tools-xml-annotation-server-xml-formatti.html?childToView=13831603)

Can we have XML formatting please for XML based files? (views mostly). This is to avoid using a separate tool for XML formatting.

Thanks!

**Comment by MN-public** [comment]
@sammok83 
Hi,
formatting capabilities are there. Feel free to try it out before the official release if you like: https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.13
Best Regards,
Mariana
