### ISSUE TITLE
An Error has occurred building context.

### ISSUE THREAD

**Issue by shubhchamp** [SAP/ui5-language-assistant#632]
Getting this error when VS code tries to load the library. 

![1](https://github.com/SAP/ui5-language-assistant/assets/26719268/7ba6690d-bb27-4ebd-8ca1-f7b76d5dabbf)
![2](https://github.com/SAP/ui5-language-assistant/assets/26719268/25abb64e-75b7-4471-9438-21e2f3e93f7b)

**Comment by mr25mr** [comment]
@shubhchamp can you please share your project or similar project to reproduce the issue and perform further analysis?
