### ISSUE TITLE
Unknown property binding info on sap:label.

### ISSUE THREAD

**Issue by vanthax** [SAP/ui5-language-assistant#637]
Using `<Label text="{oData>/SomeValue/#@sap:label} id="some_label" />` in an XMLView inside SAP BAS results in several problems showing up:
- Unknown property binding info
- Unkown character
- Missing comma
- Expect a value

This seems to be related to the colon character.

**Comment by MN-public** [comment]
@vanthax  
Thanks for reporting the issue. 
The fix is prepared. You can check it before the official release to VSC and SAP Business Application Studio by installing the extension from https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.33

**Comment by vanthax** [comment]
I wasn't able to reproduce the issue with the provided version. Thanks for quickly resolving the issue.
