### ISSUE TITLE
enhancement: Generate ID's: make this unique for a whole project (~Flexibility Services)

### ISSUE THREAD

**Issue by jvanattedev** [SAP/ui5-language-assistant#646]
If you do not have IDs for your UI5 components in the view, the UI5 Language Assistant allows you to generate IDs for the whole file. This occurs when "flexEnabled": true, in manifest.json. Unfortunately, this still generates errors in a UI5 project, since the IDs are unique in the file, but not across the whole project.

This results in errors such as:
`Error: Error: adding element with duplicate id 'application-app-tile-component---worklist--_IDGenText1'`

The request: is it possible to have the tools generate unique IDs across the whole project. This would be really useful for Flexibility Services.

**Comment by marufrasully** [comment]
Dear @jvanattedev. Your request is implemented and can be tested using `.vsix` from https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.72 
Can you please check and close this issue if everything is working as you expecting?

Thanks and regards

**Comment by jvanattedev** [comment]
Hi, I tested it with a small project. The ID's seems unique across different files now, from my test project:
- _IDGenTitle2
- _IDGenTitle1
- _IDGenLink1
- _IDGenLink

One more convenience would be to be able to generate them for the entire project in one go. Currently there are only 2 options in the Quick Fix menu:
- Generate a unique ID
- Generate unique IDs for the entire file

**Comment by MN-public** [comment]
@jvanattedev Thanks for verifying and providing the feedback.
Please create new issue for each enhancement request. I would like to close this one now as implemented
