### ISSUE TITLE
The "VBox" class can't have an empty ID attribute when flexEnabled is "true".

### ISSUE THREAD

**Issue by nevespt** [SAP/ui5-language-assistant#651]
Its possible to disable this warnings?

**Comment by MN-public** [comment]
May I first ask why would you need that?

**Comment by nevespt** [comment]
> May I first ask why would you need that?

![image](https://github.com/SAP/ui5-language-assistant/assets/50218490/5f0a3570-bb74-4014-859b-f3f7fd1e1aba)
to remove the "false errors" from the files

**Comment by nevespt** [comment]
because my code works, i just would like to disable this messages

**Comment by MN-public** [comment]
Yes, the app will work, however you won’t be able to adapt it later if you don’t have stable IDs. https://sapui5.hana.ondemand.com/sdk/#/topic/f1430c0337534d469da3a56307ff76af.html
If you don't need the app to support the adaptation capabilities, you can set the `flexEnabled` setting in manifest to `false` and the warnings will go away.

**Comment by nevespt** [comment]
thanks
