### ISSUE TITLE
Unknown property binding info on sap.ui.core.ComponentContainer

### ISSUE THREAD

**Issue by petersturmotx** [SAP/ui5-language-assistant#652]
Using 
<core:ComponentContainer id="otx_xecmcc_compcont" name="otx.xecm.corecontentbusinessworkspace" url="/sap/bc/ui5_ui5/otx/rmf_cc_ui"
					settings='{**AppMode**: false, **WidgetStyleClass**: "otx_bws_div"}'	componentCreated=".extension.customer.zxecmcc.eam.technicalobject.manages1.otx.onComponentCreated">
				</core:ComponentContainer>
in an XML view for a fragment definition in an Adaptation project in BAS raises problems related to the
settings AppMode and WidgetStyleClass with the message
"Unknown property binding info" for each.

But the component otx.xecm.corecontentbusinessworkspace with ICF URL /sap/bc/ui5_ui5/otx/rmf_cc_ui is our own SAPUI5 component deployed on the SAP backend in our own namespace.
And the properties AppMode and WidgetStyleClass are defined within our own SAPUI5 component.

At runtime, for example in the SAPUI5 Visual Editor, our component is initiated and loaded as expected.

**Comment by petersturmotx** [comment]
Perhaps if a "custom" or "partner" component name is mentioned in sap.ui5.core:ComponentContainer which is unknown to the "standard" ui5 catalog, then the property binding info messages could be made silent.

Thanks and Kind Regards,
Peter

**Comment by MN-public** [comment]
Thanks for reporting the issue, we will see what we can do

**Comment by petersturmotx** [comment]
Hi,
thanks very much. The issue is fixed. I was able to successfully verify on my BAS instance. 
Hence closing this topic.

Kind Regards,
Peter
