### ISSUE TITLE
Error SAPUI5 SDK is not accessible

### ISSUE THREAD

**Issue by Sillentium85** [SAP/ui5-language-assistant#654]
Can anybody tell me the Url that is not accessible, so that i can check it on network?
Cause i have normal Internet Connection and i dont want to setup a local Webserver for that

**Comment by MN-public** [comment]
@Sillentium85 
Hello, the Url is comprised based on the domain as defined in  https://github.com/SAP/ui5-language-assistant/blob/master/packages/context/src/types.ts#L11 and the ui5 version number set in your manifest as `minUI5Version`. 
For example if "minUI5Version": "1.116.0", the Urls would be https://sdk.openui5.org/1.116.0/ and https://ui5.sap.com/1.116.0/

So it is important to check that the `minUI5Version` value set in your manifest is supported.

**Comment by MN-public** [comment]
@Sillentium85 
I'm closing this issue as the question is answered. Feel free to reopen or create a new one if you have a follow-up question
