### ISSUE TITLE
Unknown formatter aggregation for tooltip

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-language-assistant#678]
When a formatter function is used in a tooltip aggregation...

```xml
<Text text="{title}" tooltip="{ path: 'descr', formatter: '.getTooltipText'}"/>
```

...the language assistant will raise the following error: 
```console
Unknown aggregation binding
```

**Comment by mr25mr** [comment]
@BenReim can you please share which UI5 version you are using?

**Comment by BenReim** [comment]
@mr25mr SAPUI5 `v1.120.1`

**Comment by marufrasully** [comment]
@BenReim issue is resolved. You can test it by this [vsix](https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.51). If everything works for you as expected, please close this issue. This fix will be included in upcoming release. 

Thanks.

**Comment by BenReim** [comment]
Looks good, thanks for the fix!
