### ISSUE TITLE
Local SDK: Failed to load. Will try over internet

### ISSUE THREAD

**Issue by RuckertSolutions** [SAP/ui5-language-assistant#693]
Hello,

I am behind a cooperate proxy and therefore need to load the SDK locally like explained here https://github.com/SAP/ui5-language-assistant/tree/master/examples/sap-ui5-web-server.

I got 2 SDKs running under `http://localhost:3000`. (Following UI5 versions are hosted: ["/1.71.61","/1.120.4"])

When I go to `http://localhost:3000/1.71.61/` I reach the SAP Website hosted locally.

I added the SAPUI5 Web Server setting for the extension, but I am unable to get it to work, I am getting the following error:

```
{
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "localUrl": "http://localhost:3000/1.71.61/",
  "message": "Failed to load. Will try over internet.",
  "time": "2024-02-13T09:07:17.759Z"
}
```

Complete trace after manifest initialization:

```
{
  "DEFAULT_UI5_VERSION": "1.71.61",
  "label": "@ui5-language-assistant/context",
  "level": "error",
  "message": "Could not read version mapping, fallback to default version",
  "time": "2024-02-13T09:07:17.621Z",
  "url": "https://ui5.sap.com/version.json"
}
{
  "label": "@ui5-language-assistant/context",
  "level": "warn",
  "message": "Could not read version information. Error: Version info request has failed (https://ui5.sap.com/1.120.4/resources/sap-ui-version.json)",
  "time": "2024-02-13T09:07:17.636Z",
  "url": "https://ui5.sap.com/1.120.4/resources/sap-ui-version.json"
}
{
  "framework": "SAPUI5",
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "message": "The following framework/version has been detected",
  "time": "2024-02-13T09:07:17.639Z",
  "version": "1.71.61"
}
{
  "cacheFolder": "c:\\Users\\<REDACTED>\\AppData\\Roaming\\Code\\User\\globalStorage\\saposs.vscode-ui5-language-assistant\\ui5-resources-cache\\SAPUI5\\1.71.61",
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "message": "Caching UI5 resources in",
  "time": "2024-02-13T09:07:17.640Z"
}
{
  "framework": "SAPUI5",
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "message": "building UI5 semantic Model for framework/version",
  "time": "2024-02-13T09:07:17.640Z",
  "version": "1.71.61"
}
{
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "localUrl": "http://localhost:3000/1.71.61/",
  "message": "Failed to load. Will try over internet.",
  "time": "2024-02-13T09:07:17.685Z"
}
{
  "label": "@ui5-language-assistant/context",
  "level": "warn",
  "message": "Could not read version information. Error: Version info request has failed (https://ui5.sap.com/1.71.61/resources/sap-ui-version.json)",
  "time": "2024-02-13T09:07:17.699Z",
  "url": "https://ui5.sap.com/1.71.61/resources/sap-ui-version.json"
}
{
  "label": "@ui5-language-assistant/context",
  "level": "info",
  "localUrl": "http://localhost:3000/1.71.61/",
  "message": "Failed to load. Will try over internet.",
  "time": "2024-02-13T09:07:17.759Z"
}
```

**Comment by RuckertSolutions** [comment]
Hi, thanks for the quick response.

In the manifest.json I have "minUI5Version": "1.120.4" definded (under sap.ui5.dependencies).

I tried with both "1.71.61" (default extension version) and "1.120.4" (my min version) and each one alone, but with the same result.

**Comment by RuckertSolutions** [comment]
Here is the extracted folder SDK 1.71.61 

![image](https://github.com/SAP/ui5-language-assistant/assets/20638284/cbcee898-784f-453e-9959-aa418417c936)

and here the site that I can reach locally:

![image](https://github.com/SAP/ui5-language-assistant/assets/20638284/ee9a8f11-95d0-4e1a-82fd-af958aa8fdb0)

from what I understand it *should* work no? :)

**Comment by marufrasully** [comment]
@RuckertSolutions 
can you please also cross check if you have user settings maintained.

Refer to this [documentation](https://community.sap.com/t5/technology-blogs-by-sap/sapui5-language-assistant-boosts-developer-productivity-with-building/ba-p/13550776) Search for "2. Offline work"

**Comment by RuckertSolutions** [comment]
Yes, I added the UI5LanguageAssistant.SAPUI5WebServer setting for it to use a local SDK.

settings.json: `"UI5LanguageAssistant.SAPUI5WebServer": "http://localhost:3000/",`

**Comment by RuckertSolutions** [comment]
Teams or Discord? I will be off this afternoon though; will you be available tomorrow morning? Und vielen Dank fuer die Hilfe :)

**Comment by marufrasully** [comment]
Tomorrow morning - Teams. Es gibt nichts zu danken. :)

**Comment by marufrasully** [comment]
@RuckertSolutions can you please cross check is there is any proxy settings. 

For details check this [documentation](https://www.npmjs.com/package/proxy-from-env#environment-variables).

If `HTTP_PROXY ` or `HTTPS _PROXY` is set, can you remove it or try this [work around](https://github.com/SAP/ui5-language-assistant/pull/302#issuecomment-737253345)
