### ISSUE TITLE
An error has occurred building context.

### ISSUE THREAD

**Issue by pfiffab** [SAP/ui5-language-assistant#703]
When starting to edit view.xml files I receive the error message in the title.
I can't seem to find any error messages from the plugin telling me what the issue is or where to look, can anyone help me out?

I have created a new Application with the generator so I don't think it's that. I am running on Node version 21.7.1 and UI5 Version 3.9.2.

**Comment by MN-public** [comment]
@pfiffab 
Could you please let us know what error message you see? Maybe make a screenshot?

**Comment by pfiffab** [comment]
Thanks for the quick response. My issue is that this is all I see. There is no mention or anything of where I can actually get a detailed error message. 
![image](https://github.com/SAP/ui5-language-assistant/assets/72672723/ff94a284-3c8c-4b82-9452-bfa94a535cd3)

**Comment by marufrasully** [comment]
@pfiffab 
Thanks for reporting the issue.

Is it possible to share project? If not, please share information about which generator you used to created project.

What do you mean by `UI5 Version 3.9.2.`

**Comment by MN-public** [comment]
@pfiffab 
Could you please also check and let us know the version of UI5 language assistant used in your environment and mention if you work in VSC or SAP BAS? We would also need the value of `minUI5Version` used in the `manifest.json` of your project.

JFYI: We had the similar issue in the past with some specific UI5 versions defined as `minUI5Version`, see https://github.com/SAP/ui5-language-assistant/issues/694, but it should be resolved in the latest releases of UI5 language assistant.

**Comment by pfiffab** [comment]
I work in VSC.
UI5 Language Assistant Version: 4.0.56
The generator automatically set "minUI5Version": "1.122.1".

I will try a different minUI5Version maybe, once I get back.

**Comment by pfiffab** [comment]
The generator creates a manifest.json with minUI5Version of 1.122.1 but it seems like that does not work with UI5 language assistant. Changing the minUI5Version to 1.120.0 and everything worked fine.
Should I close the issue or do you want to have a look at why the new version doesn't work?

**Comment by marufrasully** [comment]
@pfiffab 
context issue could be probably due to internet connection loading content over this link https://ui5.sap.com/1.122.1/test-resources/sap/ui/core/designtime/api.json Check if you have access to that link and correct content is loaded. 

Can you please reload window and try again with version `1.122.1`.  

Furthermore, I will add logging logic to code when it fails to build context so that more debug info is averrable when such issue is faced.

Hope that helps and best regards

**Comment by pfiffab** [comment]
I can access the information in the link without issue but when switching minUI5Version back to 1.122.1 I receive the Context error again. Really weird.
For now I can work with a lower minUI5Version, so thanks for the quick help :)

**Comment by MN-public** [comment]
@pfiffab As we did not hear back from you on this for a while, we assume it works for you with the steps outlined in https://github.com/SAP/ui5-language-assistant/issues/703#issuecomment-2039745765, so I'm closing the issue.
If you still does not work for you, please feel free to reopen with the comment on the steps above
