### ISSUE TITLE
Getting errors for duplicate IDs across different view files

### ISSUE THREAD

**Issue by patakihara** [SAP/ui5-language-assistant#729]
I'm now getting a highlighted error when using the same IDs across different view files. For instance, in the file `ShopItemListReport.view.xml`:

```
Select a unique ID. The current "dynamicPageId" ID has already been used. UI5 Language Assistant
ShopPackageListReport.view.xml(13, 12): An identical ID is also used here.
```

I have some generic controller classes that I reuse across similar views, and they depend on those views having controls with particular IDs, so this would break many of my implementations. This "error" wasn't being highlighted before, and I'm not exactly sure what caused it to be highlighted. I first noticed when updating my project's dependencies, but checking out an earlier branch hasn't prevented it from showing up again.

Is there a way to disable this check?

Someone else has come up with this issue recently and reported it here: iljapostnovs/VSCodeUI5Plugin#422

This may also be related to #646

**Comment by RagabAhmed** [comment]
Yes we are getting the same error with the new update, rolling back to version 4.0.66 solved it, but I wonder what is the reasoning behind this addition.

**Comment by MN-public** [comment]
@patakihara 
Thanks for your feedback. This is a new feature added recently based on this enhancement request: https://github.com/SAP/ui5-language-assistant/issues/646
We can think if we would like to convert these error messages to warnings or handle them otherwise, as in many cases non-unique IDs in different files do brake the app in runtime

**Comment by MN-public** [comment]
@patakihara Thanks for explaining your use case. We will see what we can do.

**Comment by s-v-o** [comment]
I would also vote for the possibility to disabling this message.
Also I see no use to make the control ids view dependent and producing an error when using this id in different views.

**Comment by marufrasully** [comment]
@patakihara we have provided user settings to limit diagnostic reporting on unique ids. You can download [v4.0.75](https://github.com/SAP/ui5-language-assistant/releases/tag/v4.0.75) and test it.Early feedback is highly appreciated. :)
User setting by default is not set, you can set it to limit diagnostic reporting. The settings looks like:
![image](https://github.com/user-attachments/assets/84e6b664-3f21-4024-bb7c-3788d1a5d889)

If this setting solves your issue, please close this issue. Thanks a lot.
