### ISSUE TITLE
Overly strict unique ID warnings

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-language-assistant#737]
The plugin is currently overly strict in checking for unique IDs:

```console
Select a unique ID. The current "myControl" ID has already been used
```

It raises error messages, even if there is no actual issue.Two cases as example: 
1. Same ID `myControl`, but used in different UI5 views (e.g. `Overview.view.xml`, `Details.view.xml`)
   → no actual issue during runtime as IDs are scoped / auto-prefixed

2. Same ID `myControl`, but used across different Fiori Apps in a CAP Project, e.g.:
    ```text
    my-project/
    ├── app/
    │   ├── admin
    │   └── viewer
    └── package.json
    ```

**Comment by MN-public** [comment]
HI @BenReim,
in many cases such validation is useful, in others it is not relevant or overly strict.
You can control this to match your needs via the newly introduced user setting `UI5LanguageAssistant.LimitUniqueIdDiagnostics`
Please check XML View Validations section in the readme file or here: https://marketplace.visualstudio.com/items?itemName=SAPOSS.vscode-ui5-language-assistant

**Comment by MN-public** [comment]
@BenReim 
No problem, I'm glad I could help
JFYI: One of the reasons is mentioned in this enhancement request: https://github.com/SAP/ui5-language-assistant/issues/646
